general {
    lock_cmd = pidof swaylock || swaylock -f -i ~/.config/wallpapers/firewatch-01-blur-0x25.jpeg
}

listener {
    # 600 s = 10 min
    timeout = 600
    on-timeout = loginctl lock-session
}
